package StepsDefinition;

import io.cucumber.java.en.*;

public class PostUserSteps {
	@Given("Autogenerated Userid and valid User schema in Json format")
	public void autogenerated_userid_and_valid_user_schema_in_json_format() {
		//System.out.println("POST request send with Valid schema");
	}

	@When("POST Request send")
	public void post_request_send(){
	   
	}
	@Then("Display Successfully Created")
	public void display_successfully_created() {
		System.out.println("Successfully Created");
	}
	

	@Given("Entered Invalid User schema in Json foramt")
	public void entered_invalid_user_schema_in_json_foramt() {
		//System.out.println("POSt request send with Invalid schema");
	    
	}

	@Then("Display Failed To Created . Status code {int}")
	public void display_failed_to_created_status_code(Integer int1) {
		System.out.println("Failed To Created . Status code {int1}");
	}
}
